name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main # Trigger on pull requests to the main branch

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Go environment
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20 # Specify your Go version

    
    - name: Install dependencies
      run: go mod tidy

  
    - name: Run tests
      run: go test ./... -v

   
    - name: Build application
      run: go build -o main .

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: build 
    steps:
   
    - name: Checkout code
      uses: actions/checkout@v3

    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 

    - name: Build and push Docker image
      run: |
        docker build -t my-app:${{ github.sha }} .
        docker tag my-app:${{ github.sha }} my-dockerhub-username/my-app:latest
        docker push my-dockerhub-username/my-app:latest

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no user@your-server-ip "docker pull my-dockerhub-username/my-app:latest && docker stop app || true && docker rm app || true && docker run -d --name app -p 8080:8080 my-dockerhub-username/my-app:latest"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
