name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Go environment
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20  # Specify your Go version

    # Install dependencies
    - name: Install dependencies
      run: go mod tidy

    # Run tests
    - name: Run tests
      run: go test ./... -v

    # Build the Go application
    - name: Build application
      run: go build -o main .

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: build  # Wait for the build job to complete

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push Docker image
    - name: Build and push Docker image
      run: |
        docker build -t stock-simulater:${{ github.sha }} .
        docker tag stock-simulater:${{ github.sha }} razim20/stock-simulater:latest
        docker push razim20/stock-simulater:latest

    # Deploy to Server
    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no user@192.168.1.39 "docker pull razim20/stock-simulater:latest && docker stop app || true && docker rm app || true && docker run -d --name app -p 8080:8080 razim20/stock-simulater:latest"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
